
/*
   DO NOT EDIT THIS FILE!

   This file is automatically generated by hpy.tools.autogen.pyUU_decls_and_stubs.autogen_decls_h_PyUU
   See also hpy.tools.autogen and hpy/tools/public_api.h

   Run this to regenerate:
       make autogen

*/

extern HPy HPyModule_Create(HPyContext ctx, HPyModuleDef *def) ;

extern HPy HPy_Dup(HPyContext ctx, HPy h) ;

extern void HPy_Close(HPyContext ctx, HPy h) ;

extern HPy HPyLong_FromLong(HPyContext ctx, long value) ;

extern HPy HPyLong_FromUnsignedLong(HPyContext ctx, unsigned long value) ;

extern HPy HPyLong_FromLongLong(HPyContext ctx, long long v) ;

extern HPy HPyLong_FromUnsignedLongLong(HPyContext ctx, unsigned long long v) ;

extern HPy HPyLong_FromSize_t(HPyContext ctx, size_t value) ;

extern HPy HPyLong_FromSsize_t(HPyContext ctx, HPy_ssize_t value) ;

extern long HPyLong_AsLong(HPyContext ctx, HPy h) ;

extern unsigned long HPyLong_AsUnsignedLong(HPyContext ctx, HPy h) ;

extern unsigned long HPyLong_AsUnsignedLongMask(HPyContext ctx, HPy h) ;

extern long long HPyLong_AsLongLong(HPyContext ctx, HPy h) ;

extern unsigned long long HPyLong_AsUnsignedLongLong(HPyContext ctx, HPy h) ;

extern unsigned long long HPyLong_AsUnsignedLongLongMask(HPyContext ctx, HPy h) ;

extern size_t HPyLong_AsSize_t(HPyContext ctx, HPy h) ;

extern HPy_ssize_t HPyLong_AsSsize_t(HPyContext ctx, HPy h) ;

extern HPy HPyFloat_FromDouble(HPyContext ctx, double v) ;

extern double HPyFloat_AsDouble(HPyContext ctx, HPy h) ;

extern HPy_ssize_t HPy_Length(HPyContext ctx, HPy h) ;

extern int HPyNumber_Check(HPyContext ctx, HPy h) ;

extern HPy HPy_Add(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_Subtract(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_Multiply(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_MatrixMultiply(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_FloorDivide(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_TrueDivide(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_Remainder(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_Divmod(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_Power(HPyContext ctx, HPy h1, HPy h2, HPy h3) ;

extern HPy HPy_Negative(HPyContext ctx, HPy h1) ;

extern HPy HPy_Positive(HPyContext ctx, HPy h1) ;

extern HPy HPy_Absolute(HPyContext ctx, HPy h1) ;

extern HPy HPy_Invert(HPyContext ctx, HPy h1) ;

extern HPy HPy_Lshift(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_Rshift(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_And(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_Xor(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_Or(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_Index(HPyContext ctx, HPy h1) ;

extern HPy HPy_Long(HPyContext ctx, HPy h1) ;

extern HPy HPy_Float(HPyContext ctx, HPy h1) ;

extern HPy HPy_InPlaceAdd(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_InPlaceSubtract(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_InPlaceMultiply(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_InPlaceMatrixMultiply(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_InPlaceFloorDivide(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_InPlaceTrueDivide(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_InPlaceRemainder(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_InPlacePower(HPyContext ctx, HPy h1, HPy h2, HPy h3) ;

extern HPy HPy_InPlaceLshift(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_InPlaceRshift(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_InPlaceAnd(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_InPlaceXor(HPyContext ctx, HPy h1, HPy h2) ;

extern HPy HPy_InPlaceOr(HPyContext ctx, HPy h1, HPy h2) ;

extern void HPyErr_SetString(HPyContext ctx, HPy h_type, const char *message) ;

extern void HPyErr_SetObject(HPyContext ctx, HPy h_type, HPy h_value) ;

extern int HPyErr_Occurred(HPyContext ctx) ;

extern HPy HPyErr_NoMemory(HPyContext ctx) ;

extern void HPyErr_Clear(HPyContext ctx) ;

extern int HPy_IsTrue(HPyContext ctx, HPy h) ;

extern HPy HPyType_FromSpec(HPyContext ctx, HPyType_Spec *spec, HPyType_SpecParam *params) ;

extern HPy HPyType_GenericNew(HPyContext ctx, HPy type, HPy *args, HPy_ssize_t nargs, HPy kw) ;

extern HPy HPy_GetAttr(HPyContext ctx, HPy obj, HPy name) ;

extern HPy HPy_GetAttr_s(HPyContext ctx, HPy obj, const char *name) ;

extern int HPy_HasAttr(HPyContext ctx, HPy obj, HPy name) ;

extern int HPy_HasAttr_s(HPyContext ctx, HPy obj, const char *name) ;

extern int HPy_SetAttr(HPyContext ctx, HPy obj, HPy name, HPy value) ;

extern int HPy_SetAttr_s(HPyContext ctx, HPy obj, const char *name, HPy value) ;

extern HPy HPy_GetItem(HPyContext ctx, HPy obj, HPy key) ;

extern HPy HPy_GetItem_i(HPyContext ctx, HPy obj, HPy_ssize_t idx) ;

extern HPy HPy_GetItem_s(HPyContext ctx, HPy obj, const char *key) ;

extern int HPy_SetItem(HPyContext ctx, HPy obj, HPy key, HPy value) ;

extern int HPy_SetItem_i(HPyContext ctx, HPy obj, HPy_ssize_t idx, HPy value) ;

extern int HPy_SetItem_s(HPyContext ctx, HPy obj, const char *key, HPy value) ;

extern void *_HPy_Cast(HPyContext ctx, HPy h) ;

extern HPy _HPy_New(HPyContext ctx, HPy h_type, void **data) ;

extern HPy HPy_Repr(HPyContext ctx, HPy obj) ;

extern HPy HPy_Str(HPyContext ctx, HPy obj) ;

extern HPy HPy_ASCII(HPyContext ctx, HPy obj) ;

extern HPy HPy_Bytes(HPyContext ctx, HPy obj) ;

extern HPy HPy_RichCompare(HPyContext ctx, HPy v, HPy w, int op) ;

extern int HPy_RichCompareBool(HPyContext ctx, HPy v, HPy w, int op) ;

extern HPy_hash_t HPy_Hash(HPyContext ctx, HPy obj) ;

extern int HPyBytes_Check(HPyContext ctx, HPy h) ;

extern HPy_ssize_t HPyBytes_Size(HPyContext ctx, HPy h) ;

extern HPy_ssize_t HPyBytes_GET_SIZE(HPyContext ctx, HPy h) ;

extern char *HPyBytes_AsString(HPyContext ctx, HPy h) ;

extern char *HPyBytes_AS_STRING(HPyContext ctx, HPy h) ;

extern HPy HPyBytes_FromString(HPyContext ctx, const char *v) ;

extern HPy HPyBytes_FromStringAndSize(HPyContext ctx, const char *v, HPy_ssize_t len) ;

extern HPy HPyUnicode_FromString(HPyContext ctx, const char *utf8) ;

extern int HPyUnicode_Check(HPyContext ctx, HPy h) ;

extern HPy HPyUnicode_AsUTF8String(HPyContext ctx, HPy h) ;

extern HPy HPyUnicode_FromWideChar(HPyContext ctx, const wchar_t *w, HPy_ssize_t size) ;

extern int HPyList_Check(HPyContext ctx, HPy h) ;

extern HPy HPyList_New(HPyContext ctx, HPy_ssize_t len) ;

extern int HPyList_Append(HPyContext ctx, HPy h_list, HPy h_item) ;

extern int HPyDict_Check(HPyContext ctx, HPy h) ;

extern HPy HPyDict_New(HPyContext ctx) ;

extern void HPy_FatalError(HPyContext ctx, const char *message) ;

extern HPy HPyTuple_FromArray(HPyContext ctx, HPy items[], HPy_ssize_t n) ;

extern HPy HPy_FromPyObject(HPyContext ctx, cpy_PyObject *obj) ;

extern cpy_PyObject *HPy_AsPyObject(HPyContext ctx, HPy h) ;

extern void _HPy_CallRealFunctionFromTrampoline(HPyContext ctx, HPyFunc_Signature sig, void *func, void *args) ;

extern void _HPy_CallDestroyAndThenDealloc(HPyContext ctx, void *func, cpy_PyObject *self) ;

extern HPyListBuilder HPyListBuilder_New(HPyContext ctx, HPy_ssize_t initial_size) ;

extern void HPyListBuilder_Set(HPyContext ctx, HPyListBuilder builder, HPy_ssize_t index, HPy h_item) ;

extern HPy HPyListBuilder_Build(HPyContext ctx, HPyListBuilder builder) ;

extern void HPyListBuilder_Cancel(HPyContext ctx, HPyListBuilder builder) ;

extern HPyTupleBuilder HPyTupleBuilder_New(HPyContext ctx, HPy_ssize_t initial_size) ;

extern void HPyTupleBuilder_Set(HPyContext ctx, HPyTupleBuilder builder, HPy_ssize_t index, HPy h_item) ;

extern HPy HPyTupleBuilder_Build(HPyContext ctx, HPyTupleBuilder builder) ;

extern void HPyTupleBuilder_Cancel(HPyContext ctx, HPyTupleBuilder builder) ;

extern HPyTracker HPyTracker_New(HPyContext ctx, HPy_ssize_t size) ;

extern int HPyTracker_Add(HPyContext ctx, HPyTracker ht, HPy h) ;

extern void HPyTracker_ForgetAll(HPyContext ctx, HPyTracker ht) ;

extern void HPyTracker_Close(HPyContext ctx, HPyTracker ht) ;

