
/*
   DO NOT EDIT THIS FILE!

   This file is automatically generated by hpy.tools.autogen.pyUU_decls_and_stubs.autogen_ctx_vtable
   See also hpy.tools.autogen and hpy/tools/public_api.h

   Run this to regenerate:
       make autogen

*/

ctx->ctx_Module_Create = HPyModule_Create;
ctx->ctx_Dup = HPy_Dup;
ctx->ctx_Close = HPy_Close;
ctx->ctx_Long_FromLong = HPyLong_FromLong;
ctx->ctx_Long_FromUnsignedLong = HPyLong_FromUnsignedLong;
ctx->ctx_Long_FromLongLong = HPyLong_FromLongLong;
ctx->ctx_Long_FromUnsignedLongLong = HPyLong_FromUnsignedLongLong;
ctx->ctx_Long_FromSize_t = HPyLong_FromSize_t;
ctx->ctx_Long_FromSsize_t = HPyLong_FromSsize_t;
ctx->ctx_Long_AsLong = HPyLong_AsLong;
ctx->ctx_Long_AsUnsignedLong = HPyLong_AsUnsignedLong;
ctx->ctx_Long_AsUnsignedLongMask = HPyLong_AsUnsignedLongMask;
ctx->ctx_Long_AsLongLong = HPyLong_AsLongLong;
ctx->ctx_Long_AsUnsignedLongLong = HPyLong_AsUnsignedLongLong;
ctx->ctx_Long_AsUnsignedLongLongMask = HPyLong_AsUnsignedLongLongMask;
ctx->ctx_Long_AsSize_t = HPyLong_AsSize_t;
ctx->ctx_Long_AsSsize_t = HPyLong_AsSsize_t;
ctx->ctx_Float_FromDouble = HPyFloat_FromDouble;
ctx->ctx_Float_AsDouble = HPyFloat_AsDouble;
ctx->ctx_Length = HPy_Length;
ctx->ctx_Number_Check = HPyNumber_Check;
ctx->ctx_Add = HPy_Add;
ctx->ctx_Subtract = HPy_Subtract;
ctx->ctx_Multiply = HPy_Multiply;
ctx->ctx_MatrixMultiply = HPy_MatrixMultiply;
ctx->ctx_FloorDivide = HPy_FloorDivide;
ctx->ctx_TrueDivide = HPy_TrueDivide;
ctx->ctx_Remainder = HPy_Remainder;
ctx->ctx_Divmod = HPy_Divmod;
ctx->ctx_Power = HPy_Power;
ctx->ctx_Negative = HPy_Negative;
ctx->ctx_Positive = HPy_Positive;
ctx->ctx_Absolute = HPy_Absolute;
ctx->ctx_Invert = HPy_Invert;
ctx->ctx_Lshift = HPy_Lshift;
ctx->ctx_Rshift = HPy_Rshift;
ctx->ctx_And = HPy_And;
ctx->ctx_Xor = HPy_Xor;
ctx->ctx_Or = HPy_Or;
ctx->ctx_Index = HPy_Index;
ctx->ctx_Long = HPy_Long;
ctx->ctx_Float = HPy_Float;
ctx->ctx_InPlaceAdd = HPy_InPlaceAdd;
ctx->ctx_InPlaceSubtract = HPy_InPlaceSubtract;
ctx->ctx_InPlaceMultiply = HPy_InPlaceMultiply;
ctx->ctx_InPlaceMatrixMultiply = HPy_InPlaceMatrixMultiply;
ctx->ctx_InPlaceFloorDivide = HPy_InPlaceFloorDivide;
ctx->ctx_InPlaceTrueDivide = HPy_InPlaceTrueDivide;
ctx->ctx_InPlaceRemainder = HPy_InPlaceRemainder;
ctx->ctx_InPlacePower = HPy_InPlacePower;
ctx->ctx_InPlaceLshift = HPy_InPlaceLshift;
ctx->ctx_InPlaceRshift = HPy_InPlaceRshift;
ctx->ctx_InPlaceAnd = HPy_InPlaceAnd;
ctx->ctx_InPlaceXor = HPy_InPlaceXor;
ctx->ctx_InPlaceOr = HPy_InPlaceOr;
ctx->ctx_Err_SetString = HPyErr_SetString;
ctx->ctx_Err_SetObject = HPyErr_SetObject;
ctx->ctx_Err_Occurred = HPyErr_Occurred;
ctx->ctx_Err_NoMemory = HPyErr_NoMemory;
ctx->ctx_Err_Clear = HPyErr_Clear;
ctx->ctx_IsTrue = HPy_IsTrue;
ctx->ctx_Type_FromSpec = HPyType_FromSpec;
ctx->ctx_Type_GenericNew = HPyType_GenericNew;
ctx->ctx_GetAttr = HPy_GetAttr;
ctx->ctx_GetAttr_s = HPy_GetAttr_s;
ctx->ctx_HasAttr = HPy_HasAttr;
ctx->ctx_HasAttr_s = HPy_HasAttr_s;
ctx->ctx_SetAttr = HPy_SetAttr;
ctx->ctx_SetAttr_s = HPy_SetAttr_s;
ctx->ctx_GetItem = HPy_GetItem;
ctx->ctx_GetItem_i = HPy_GetItem_i;
ctx->ctx_GetItem_s = HPy_GetItem_s;
ctx->ctx_SetItem = HPy_SetItem;
ctx->ctx_SetItem_i = HPy_SetItem_i;
ctx->ctx_SetItem_s = HPy_SetItem_s;
ctx->ctx_Repr = HPy_Repr;
ctx->ctx_Str = HPy_Str;
ctx->ctx_ASCII = HPy_ASCII;
ctx->ctx_Bytes = HPy_Bytes;
ctx->ctx_RichCompare = HPy_RichCompare;
ctx->ctx_RichCompareBool = HPy_RichCompareBool;
ctx->ctx_Hash = HPy_Hash;
ctx->ctx_Bytes_Check = HPyBytes_Check;
ctx->ctx_Bytes_Size = HPyBytes_Size;
ctx->ctx_Bytes_GET_SIZE = HPyBytes_GET_SIZE;
ctx->ctx_Bytes_AsString = HPyBytes_AsString;
ctx->ctx_Bytes_AS_STRING = HPyBytes_AS_STRING;
ctx->ctx_Bytes_FromString = HPyBytes_FromString;
ctx->ctx_Bytes_FromStringAndSize = HPyBytes_FromStringAndSize;
ctx->ctx_Unicode_FromString = HPyUnicode_FromString;
ctx->ctx_Unicode_Check = HPyUnicode_Check;
ctx->ctx_Unicode_AsUTF8String = HPyUnicode_AsUTF8String;
ctx->ctx_Unicode_FromWideChar = HPyUnicode_FromWideChar;
ctx->ctx_List_Check = HPyList_Check;
ctx->ctx_List_New = HPyList_New;
ctx->ctx_List_Append = HPyList_Append;
ctx->ctx_Dict_Check = HPyDict_Check;
ctx->ctx_Dict_New = HPyDict_New;
ctx->ctx_FatalError = HPy_FatalError;
ctx->ctx_Tuple_FromArray = HPyTuple_FromArray;
ctx->ctx_FromPyObject = HPy_FromPyObject;
ctx->ctx_AsPyObject = HPy_AsPyObject;
ctx->ctx_ListBuilder_New = HPyListBuilder_New;
ctx->ctx_ListBuilder_Set = HPyListBuilder_Set;
ctx->ctx_ListBuilder_Build = HPyListBuilder_Build;
ctx->ctx_ListBuilder_Cancel = HPyListBuilder_Cancel;
ctx->ctx_TupleBuilder_New = HPyTupleBuilder_New;
ctx->ctx_TupleBuilder_Set = HPyTupleBuilder_Set;
ctx->ctx_TupleBuilder_Build = HPyTupleBuilder_Build;
ctx->ctx_TupleBuilder_Cancel = HPyTupleBuilder_Cancel;
ctx->ctx_Tracker_New = HPyTracker_New;
ctx->ctx_Tracker_Add = HPyTracker_Add;
ctx->ctx_Tracker_ForgetAll = HPyTracker_ForgetAll;
ctx->ctx_Tracker_Close = HPyTracker_Close;
